In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import numpy as np

customers = pd.read_csv("olist_customers_dataset.csv.zip")
orders = pd.read_csv("olist_orders_dataset.csv.zip")
order_items = pd.read_csv("olist_order_items_dataset.csv.zip")
payments = pd.read_csv("olist_order_payments_dataset.csv.zip")
products = pd.read_csv("olist_products_dataset.csv.zip")
reviews = pd.read_csv("olist_order_reviews_dataset.csv.zip")

# These are normal CSV files
sellers = pd.read_csv("olist_sellers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv.zip")
translation = pd.read_csv("product_category_name_translation.csv")

In [ ]:
def check_duplicates(df, name):

    duplicates = df.duplicated().sum()

    print("="*60)
    print(name)
    print("="*60)
    print(f"Duplicate Rows : {duplicates}")

In [ ]:
check_duplicates(customers,"Customers")
check_duplicates(orders,"Orders")
check_duplicates(order_items,"Order Items")
check_duplicates(payments,"Payments")
check_duplicates(reviews,"Reviews")
check_duplicates(products,"Products")
check_duplicates(sellers,"Sellers")
check_duplicates(geolocation,"Geolocation")

============================================================
Customers
============================================================
Duplicate Rows : 0
============================================================
Orders
============================================================
Duplicate Rows : 0
============================================================
Order Items
============================================================
Duplicate Rows : 0
============================================================
Payments
============================================================
Duplicate Rows : 0
============================================================
Reviews
============================================================
Duplicate Rows : 0
============================================================
Products
============================================================
Duplicate Rows : 0
============================================================
Sellers
============================================================
Duplicate Rows : 0
============================================================
Geolocation
============================================================
Duplicate Rows : 261831

In [ ]:
geolocation[geolocation.duplicated()].head(20)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
72,1046,-23.545320,-46.644069,sao paulo,SP
79,1050,-23.549854,-46.643139,sao paulo,SP
80,1032,-23.540775,-46.635515,sao paulo,SP
82,1046,-23.546081,-46.644820,sao paulo,SP
86,1048,-23.547449,-46.640169,são paulo,SP
89,1036,-23.541700,-46.641318,sao paulo,SP
91,1013,-23.547325,-46.634184,sao paulo,SP
94,1046,-23.546081,-46.644820,sao paulo,SP
95,1046,-23.546129,-46.642951,sao paulo,SP
97,1009,-23.546341,-46.636239,sao paulo,SP
102,1009,-23.546341,-46.636239,sao paulo,SP
104,1050,-23.549107,-46.644105,são paulo,SP
106,1047,-23.546273,-46.641225,sao paulo,SP
111,1032,-23.537020,-46.634359,sao paulo,SP
114,1005,-23.549819,-46.635606,sao paulo,SP

In [ ]:
print("Total Rows:", len(geolocation))

print("Unique ZIP Codes:", geolocation["geolocation_zip_code_prefix"].nunique())

Total Rows: 1000163
Unique ZIP Codes: 19015

In [ ]:
geolocation[
    geolocation.duplicated(keep=False)
].sort_values("geolocation_zip_code_prefix").head(20)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
851,1001,-23.549825,-46.633970,sao paulo,SP
1062,1001,-23.550498,-46.634338,sao paulo,SP
1246,1001,-23.549292,-46.633559,sao paulo,SP
897,1001,-23.549292,-46.633559,sao paulo,SP
99,1001,-23.549292,-46.633559,sao paulo,SP
864,1001,-23.549825,-46.633970,sao paulo,SP
771,1001,-23.550498,-46.634338,sao paulo,SP
818,1001,-23.551337,-46.634027,sao paulo,SP
1384,1001,-23.549292,-46.633559,sao paulo,SP
429,1001,-23.550498,-46.634338,sao paulo,SP
583,1001,-23.551337,-46.634027,sao paulo,SP
519,1001,-23.551337,-46.634027,sao paulo,SP
639,1001,-23.550498,-46.634338,sao paulo,SP
1004,1001,-23.549292,-46.633559,sao paulo,SP
985,1001,-23.550498,-46.634338,sao paulo,SP
912,1001,-23.550498,-46.634338,sao paulo,SP
1435,1001,-23.549292,-46.633559,sao paulo,SP
596,1001,-23.550498,-46.634338,sao paulo,SP
206,1001,-23.550498,-46.634338,sao paulo,SP
1328,1002,-23.548551,-46.635072,sao paulo,SP

# Missing Value Analysis

In [ ]:
def missing_summary(df, name):

    missing = df.isnull().sum()
    missing = missing[missing > 0]

    print("=" * 70)
    print(name)
    print("=" * 70)

    if len(missing) == 0:
        print("No Missing Values")

    else:
        result = pd.DataFrame({
            "Missing Values": missing,
            "Percentage": round((missing / len(df)) * 100, 2)
        })

        display(result.sort_values("Percentage", ascending=False))

In [ ]:
missing_summary(customers, "Customers")
missing_summary(orders, "Orders")
missing_summary(order_items, "Order Items")
missing_summary(products, "Products")
missing_summary(payments, "Payments")
missing_summary(reviews, "Reviews")
missing_summary(sellers, "Sellers")
missing_summary(geolocation, "Geolocation")

======================================================================
Customers
======================================================================
No Missing Values
======================================================================
Orders
======================================================================

                               Missing Values  Percentage
order_delivered_customer_date            2965        2.98
order_delivered_carrier_date             1783        1.79
order_approved_at                         160        0.16

======================================================================
Order Items
======================================================================
No Missing Values
======================================================================
Products
======================================================================

                            Missing Values  Percentage
product_category_name                  610        1.85
product_name_lenght                    610        1.85
product_description_lenght             610        1.85
product_photos_qty                     610        1.85
product_weight_g                         2        0.01
product_length_cm                        2        0.01
product_height_cm                        2        0.01
product_width_cm                         2        0.01

======================================================================
Payments
======================================================================
No Missing Values
======================================================================
Reviews
======================================================================

                        Missing Values  Percentage
review_comment_title             87656       88.34
review_comment_message           58247       58.70

======================================================================
Sellers
======================================================================
No Missing Values
======================================================================
Geolocation
======================================================================
No Missing Values

In [ ]:
orders[orders["order_delivered_customer_date"].isnull()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

## Missing Value Decision - Orders

The missing values in the delivery-related columns are not random.

They represent valid business scenarios such as:

- Cancelled orders
- Unavailable products
- Orders still in processing or shipment

Therefore, these missing values are retained because they provide meaningful business information.

In [ ]:
products["product_category_name"] = products["product_category_name"].fillna("Unknown")
products["product_weight_g"] = products["product_weight_g"].fillna(products["product_weight_g"].median())

products["product_length_cm"] = products["product_length_cm"].fillna(products["product_length_cm"].median())

products["product_height_cm"] = products["product_height_cm"].fillna(products["product_height_cm"].median())

products["product_width_cm"] = products["product_width_cm"].fillna(products["product_width_cm"].median())

In [ ]:
reviews["review_comment_title"] = reviews["review_comment_title"].fillna("No Title")
reviews["review_comment_message"] = reviews["review_comment_message"].fillna("No Comment")

In [ ]:
reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [ ]:
products.isnull().sum()

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
dtype: int64

#Convert Date Columns

In [ ]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

reviews["review_creation_date"] = pd.to_datetime(reviews["review_creation_date"])
reviews["review_answer_timestamp"] = pd.to_datetime(reviews["review_answer_timestamp"])

In [ ]:
print("Customer IDs duplicated:", customers["customer_id"].duplicated().sum())

print("Order IDs duplicated:", orders["order_id"].duplicated().sum())

print("Product IDs duplicated:", products["product_id"].duplicated().sum())

print("Seller IDs duplicated:", sellers["seller_id"].duplicated().sum())

Customer IDs duplicated: 0
Order IDs duplicated: 0
Product IDs duplicated: 0
Seller IDs duplicated: 0

Conclusion: All primary keys are valid.

In [ ]:
print(orders[
        ~orders["customer_id"].isin(customers["customer_id"])
    ].shape)

print(
    order_items[
        ~order_items["order_id"].isin(orders["order_id"])
    ].shape
)

print(
    order_items[
        ~order_items["product_id"].isin(products["product_id"])
    ].shape
)

(0, 8)
(0, 7)
(0, 7)

This means:

Every order belongs to a valid customer.
Every order item belongs to a valid order.
Every product in order_items exists in the products table.

In [ ]:
customers.to_csv("customers_clean.csv", index=False)
orders.to_csv("orders_clean.csv", index=False)
order_items.to_csv("order_items_clean.csv", index=False)
products.to_csv("products_clean.csv", index=False)
payments.to_csv("payments_clean.csv", index=False)
reviews.to_csv("reviews_clean.csv", index=False)