In [ ]:
import pandas as pd
import numpy as np

customers = pd.read_csv("olist_customers_dataset.csv.zip")
orders = pd.read_csv("olist_orders_dataset.csv.zip")
order_items = pd.read_csv("olist_order_items_dataset.csv.zip")
products = pd.read_csv("olist_products_dataset.csv.zip")
payments = pd.read_csv("olist_order_payments_dataset.csv.zip")
reviews = pd.read_csv("olist_order_reviews_dataset.csv.zip")
sellers = pd.read_csv("olist_sellers_dataset.csv")
translation = pd.read_csv("product_category_name_translation.csv")

In [ ]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

#Understand the Relationships

```
Customers
     │
customer_id
     │
     ▼
Orders
     │
order_id
     │
     ▼
Order Items
     │
product_id
     ▼
Products

In [ ]:
customer360 = orders.copy()
customer360.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [ ]:
customer360 = customer360.merge(
    customers,
    on="customer_id",
    how="left"
)
customer360.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id_x,customer_zip_code_prefix_x,customer_city_x,customer_state_x,customer_unique_id_y,customer_zip_code_prefix_y,customer_city_y,customer_state_y
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [ ]:
customer360 = customer360.merge(
    order_items,
    on="order_id",
    how="left"
)
customer360.shape

(113425, 22)

In [ ]:
customer360 = customer360.merge(
    products,
    on="product_id",
    how="left"
)

In [ ]:
customer360 = customer360.merge(
    payments,
    on="order_id",
    how="left"
)

In [ ]:
customer360 = customer360.merge(
    reviews,
    on="order_id",
    how="left"
)

In [ ]:
customer360.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id_x,customer_zip_code_prefix_x,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58

In [ ]:
customer360.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  datetime64[ns]
 4   order_approved_at              118966 non-null  datetime64[ns]
 5   order_delivered_carrier_date   117057 non-null  datetime64[ns]
 6   order_delivered_customer_date  115722 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119143 non-null  datetime64[ns]
 8   customer_unique_id_x           119143 non-null  object
 9   customer_zip_code_prefix_x     119143 non-null  int64
 10  customer_city_x                119143 non-null  object
 11  customer_state_x               119143 non-null  object
 12  customer_unique_id_y           119143 non-null  object
 13  customer_zip_code_prefix_y     119143 non-null  int64
 14  customer_city_y                119143 non-null  object
 15  customer_state_y               119143 non-null  object
 16  order_item_id                  118310 non-null  float64
 17  product_id                     118310 non-null  object
 18  seller_id                      118310 non-null  object
 19  shipping_limit_date            118310 non-null  object
 20  price                          118310 non-null  float64
 21  freight_value                  118310 non-null  float64
 22  product_category_name          116601 non-null  object
 23  product_name_lenght            116601 non-null  float64
 24  product_description_lenght     116601 non-null  float64
 25  product_photos_qty             116601 non-null  float64
 26  product_weight_g               118290 non-null  float64
 27  product_length_cm              118290 non-null  float64
 28  product_height_cm              118290 non-null  float64
 29  product_width_cm               118290 non-null  float64
 30  payment_sequential             119140 non-null  float64
 31  payment_type                   119140 non-null  object
 32  payment_installments           119140 non-null  float64
 33  payment_value                  119140 non-null  float64
 34  review_id                      118146 non-null  object
 35  review_score                   118146 non-null  float64
 36  review_comment_title           13989 non-null   object
 37  review_comment_message         50245 non-null   object
 38  review_creation_date           118146 non-null  object
 39  review_answer_timestamp        118146 non-null  object
dtypes: datetime64[ns](5), float64(14), int64(2), object(19)
memory usage: 36.4+ MB

In [ ]:
customer360.shape

(119143, 40)

In [ ]:
customer360.to_csv("customer360_master.csv", index=False)

Date Features

In [ ]:
customer360['Purchase_Year'] = customer360['order_purchase_timestamp'].dt.year
customer360['Purchase_Month'] = customer360['order_purchase_timestamp'].dt.month_name()
customer360['Purchase_Quarter'] = customer360['order_purchase_timestamp'].dt.quarter
customer360['Purchase_Day'] = customer360['order_purchase_timestamp'].dt.day_name()

Delivery Features

In [ ]:
customer360['Delivery_Days'] = (
    customer360['order_delivered_customer_date']
    - customer360['order_purchase_timestamp']
).dt.days

customer360['Delivery_Delay'] = (
    customer360['order_delivered_customer_date']
    - customer360['order_estimated_delivery_date']
).dt.days

customer360['Delivery_Status'] = np.where(
    customer360['Delivery_Delay'] > 0,
    'Late',
    'On Time/Early'
)

Customer Features

In [ ]:
customer360.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'customer_unique_id_x',
 'customer_zip_code_prefix_x',
 'customer_city_x',
 'customer_state_x',
 'customer_unique_id_y',
 'customer_zip_code_prefix_y',
 'customer_city_y',
 'customer_state_y',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'payment_sequential',
 'payment_type',
 'payment_installments',
 'payment_value',
 'review_id',
 'review_score',
 'review_comment_title',
 'review_comment_message',
 'review_creation_date',
 'review_answer_timestamp',
 'Purchase_Year',
 'Purchase_Month',
 'Purchase_Quarter',
 'Purchase_Day',
 'Delivery_Days',
 'Delivery_Delay',
 'Delivery_Status']

In [ ]:
(customer360['customer_unique_id_x'] == customer360['customer_unique_id_y']).all()

np.True_

In [ ]:
customer360.drop(
    columns=[
        'customer_unique_id_y',
        'customer_zip_code_prefix_y',
        'customer_city_y',
        'customer_state_y'
    ],
    inplace=True
)

In [ ]:
customer360['Customer_Total_Orders'] = customer360.groupby(
    'customer_unique_id'
)['order_id'].transform('nunique')

customer360['Customer_Total_Spend'] = customer360.groupby(
    'customer_unique_id'
)['payment_value'].transform('sum')

customer360['Repeat_Customer'] = np.where(
    customer360['Customer_Total_Orders'] > 1,
    'Yes',
    'No'
)

Review Features

In [ ]:
customer360['Review_Category'] = np.where(
    customer360['review_score'] >= 4,
    'Positive',
    'Negative'
)

In [ ]:
customer360.to_csv('customer360_final.csv', index=False)

Check the new features

In [ ]:
customer360[['Purchase_Month',
             'Purchase_Quarter',
             'Delivery_Days',
             'Delivery_Delay',
             'Delivery_Status',
             'Customer_Total_Orders',
             'Customer_Total_Spend',
             'Repeat_Customer',
             'Review_Category']].head()

,Purchase_Month,Purchase_Quarter,Delivery_Days,Delivery_Delay,Delivery_Status,Customer_Total_Orders,Customer_Total_Spend,Repeat_Customer,Review_Category
0,October,4,8.0,-8.0,On Time/Early,2,82.82,Yes,Positive
1,October,4,8.0,-8.0,On Time/Early,2,82.82,Yes,Positive
2,October,4,8.0,-8.0,On Time/Early,2,82.82,Yes,Positive
3,July,3,13.0,-6.0,On Time/Early,1,141.46,No,Positive
4,August,3,9.0,-18.0,On Time/Early,1,179.12,No,Positive

In [ ]:
customer360.isnull().sum()

order_id                              0
customer_id                           0
order_status                          0
order_purchase_timestamp              0
order_approved_at                   177
order_delivered_carrier_date       2086
order_delivered_customer_date      3421
order_estimated_delivery_date         0
customer_unique_id                    0
customer_zip_code_prefix              0
customer_city                         0
customer_state                        0
order_item_id                       833
product_id                          833
seller_id                           833
shipping_limit_date                 833
price                               833
freight_value                       833
product_category_name              2542
product_name_lenght                2542
product_description_lenght         2542
product_photos_qty                 2542
product_weight_g                    853
product_length_cm                   853
product_height_cm                   853
product_width_cm                    853
payment_sequential                    3
payment_type                          3
payment_installments                  3
payment_value                         3
review_id                           997
review_score                        997
review_comment_title             105154
review_comment_message            68898
review_creation_date                997
review_answer_timestamp             997
Purchase_Year                         0
Purchase_Month                        0
Purchase_Quarter                      0
Purchase_Day                          0
Delivery_Days                      3421
Delivery_Delay                     3421
Delivery_Status                       0
Customer_Total_Orders                 0
Customer_Total_Spend                  0
Repeat_Customer                       0
Review_Category                       0
dtype: int64

In [ ]:
customer360.shape

(119143, 47)

In [ ]:
customer360['Review_Category'] = np.where(
    customer360['review_score'].isna(),
    'No Review',
    np.where(customer360['review_score'] >= 4,
             'Positive',
             'Negative')
)

In [ ]:
customer360.duplicated().sum()

np.int64(0)

In [ ]:
customer360.describe(include='all')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,Purchase_Month,Purchase_Quarter,Purchase_Day,Delivery_Days,Delivery_Delay,Delivery_Status,Customer_Total_Orders,Customer_Total_Spend,Repeat_Customer,Review_Category
count,119143,119143,119143,119143,118966,117057,115722,119143,119143,119143.000000,...,119143,119143.000000,119143,115722.000000,115722.000000,119143,119143.000000,119143.000000,119143,119143
unique,99441,99441,8,NaN,NaN,NaN,NaN,NaN,96096,NaN,...,12,NaN,7,NaN,NaN,2,NaN,NaN,2,3
top,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,NaN,NaN,NaN,NaN,NaN,9a736b248f67d166d2fbb006bcb877c3,NaN,...,August,NaN,Monday,NaN,NaN,On Time/Early,NaN,NaN,No,Positive
freq,63,63,115723,NaN,NaN,NaN,NaN,NaN,75,NaN,...,12802,NaN,19366,NaN,NaN,111584,NaN,NaN,110404,88662
mean,NaN,NaN,NaN,2017-12-29 18:36:13.115760128,2017-12-30 04:49:18.425726976,2018-01-03 08:24:34.395524864,2018-01-12 20:55:38.199616,2018-01-22 15:21:10.241642240,NaN,35033.451298,...,NaN,2.356362,NaN,12.022589,-12.048392,NaN,1.091126,383.700500,NaN,NaN
min,NaN,NaN,NaN,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30 00:00:00,NaN,1003.000000,...,NaN,1.000000,NaN,0.000000,-147.000000,NaN,1.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,2017-09-10 20:15:46,2017-09-11 15:50:48.500000,2017-09-14 19:52:12,2017-09-22 21:54:31.249999872,2017-10-02 00:00:00,NaN,11250.000000,...,NaN,1.000000,NaN,6.000000,-17.000000,NaN,1.000000,70.720000,NaN,NaN
50%,NaN,NaN,NaN,2018-01-17 11:59:12,2018-01-17 16:49:49,2018-01-23 17:03:08,2018-02-01 03:17:55,2018-02-14 00:00:00,NaN,24240.000000,...,NaN,2.000000,NaN,10.000000,-13.000000,NaN,1.000000,135.170000,NaN,NaN
75%,NaN,NaN,NaN,2018-05-03 13:18:30,2018-05-03 16:56:53,2018-05-07 14:57:00,2018-05-15 00:08:31.500000,2018-05-25 00:00:00,NaN,58475.000000,...,NaN,3.000000,NaN,15.000000,-7.000000,NaN,1.000000,283.200000,NaN,NaN
max,NaN,NaN,NaN,2018-10-17 17:30:18,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-11-12 00:00:00,NaN,99990.000000,...,NaN,4.000000,NaN,209.000000,188.000000,NaN,17.000000,109312.640000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29823.198969,...,NaN,1.063027,NaN,9.454922,10.163801,NaN,0.410960,1669.221848,NaN,NaN

In [ ]:
customer360.to_csv("customer360_final.csv", index=False)